// <auto-generated />
namespace testApp1_MVC_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedFile));
        
        string IMigrationMetadata.Id
        {
            get { return "202302080839007_addedFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
